version: "3"

services:
  server:
    build: ./server
    container_name: server
    restart: always
    env_file:
      - server.env
    volumes:
      - ./server/app/:/app
    ports:
      - 8080:8080
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080